"""empty message

Revision ID: 02054360a77c
Revises: 2589041f3d22
Create Date: 2026-03-31 22:32:31.110353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02054360a77c'
down_revision = '2589041f3d22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
