"""empty message

Revision ID: 476b89ccd626
Revises: 4f548d105e33
Create Date: 2026-03-24 10:40:02.552528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '476b89ccd626'
down_revision = '4f548d105e33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('aadhar_card_number'))
        batch_op.drop_index(batch_op.f('pan_card_number'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('pan_card_number'), ['pan_card_number'], unique=True)
        batch_op.create_index(batch_op.f('aadhar_card_number'), ['aadhar_card_number'], unique=True)

    # ### end Alembic commands ###
